#!/usr/bin/env python3
"""Generate 100 philosophers."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from people_ai_helper import person, write_people

P = []
p = lambda *a, **k: P.append(person(*a, **k))

p("socrates","Socrates","ソクラテス",-470,-399,["gr"],["philosophy"],"Socrates was an ancient Greek philosopher credited as the founder of Western philosophy. He developed the Socratic method of questioning to stimulate critical thinking.","Socrates was born in Athens. His father was a stonemason and his mother a midwife. He served in the Athenian military and later devoted himself entirely to philosophical inquiry.","Socrates' method of dialectical questioning became the foundation of Western philosophical inquiry. His emphasis on ethics, self-knowledge, and reasoned argument transformed intellectual life.",[(-432,"Served in the Peloponnesian War"),(-423,"Depicted in Aristophanes' The Clouds"),(-399,"Tried and executed for impiety and corrupting youth")],[("Socratic Method",-400,"Dialectical method of inquiry using questions to stimulate critical thinking")],[("The unexamined life is not worth living.","Plato, Apology")])

p("plato","Plato","プラトン",-428,-348,["gr"],["philosophy"],"Plato was an ancient Greek philosopher who founded the Academy in Athens, the first institution of higher learning in the Western world. His philosophical writings have shaped Western thought for millennia.","Plato was born into an aristocratic Athenian family. He became a student of Socrates and was profoundly affected by his teacher's execution in 399 BC.","Plato's theory of Forms, his political philosophy in the Republic, and his dialogues established the framework for Western metaphysics, epistemology, and political thought.",[(-399,"Witnessed the execution of Socrates"),(-387,"Founded the Academy in Athens"),(-380,"Wrote The Republic"),(-360,"Wrote Timaeus and later dialogues")],[("The Republic",-380,"Philosophical work on justice, the ideal state, and the theory of Forms"),("Symposium",-385,"Dialogue on the nature of love and beauty")],[("Be kind, for everyone you meet is fighting a hard battle.","Attributed")])

p("aristotle","Aristotle","アリストテレス",-384,-322,["gr"],["philosophy","biology"],"Aristotle was an ancient Greek philosopher and polymath whose writings cover physics, biology, metaphysics, logic, ethics, and politics. He was Plato's student and Alexander the Great's tutor.","Aristotle was born in Stagira, Chalcidice. He joined Plato's Academy at age 17 and remained there for 20 years before founding his own school, the Lyceum.","Aristotle's systematic approach to knowledge created the foundation for Western science and philosophy. His logic dominated for two millennia, and his works on ethics and politics remain studied today.",[(-367,"Joined Plato's Academy"),(-343,"Became tutor to Alexander the Great"),(-335,"Founded the Lyceum in Athens"),(-322,"Fled Athens and died in Chalcis")],[("Nicomachean Ethics",-340,"Foundational work on virtue ethics and the good life"),("Politics",-330,"Analysis of political systems and the ideal state"),("Organon",-350,"Collection of works on logic that defined the field for centuries")],[("Knowing yourself is the beginning of all wisdom.","Attributed")])

p("confucius","Confucius","孔子",-551,-479,["cn"],["philosophy"],"Confucius was a Chinese philosopher and teacher whose ideas on ethics, family, and governance profoundly shaped East Asian civilization. His teachings form the basis of Confucianism.","Confucius was born in the state of Lu in present-day Shandong province. From a modest background, he devoted himself to learning and teaching from an early age.","Confucius's emphasis on moral cultivation, filial piety, ritual propriety, and benevolent governance shaped Chinese culture and influenced all of East Asia for over two millennia.",[(-531,"Began teaching students"),(-501,"Served as Minister of Crime in Lu"),(-497,"Began 14-year wandering period"),(-484,"Returned to Lu and focused on teaching")],[("Analerta",-479,"Collection of Confucius's sayings and teachings compiled by his disciples")],[("It does not matter how slowly you go as long as you do not stop.","Attributed")])

p("laozi","Laozi","老子",-601,-531,["cn"],["philosophy"],"Laozi was an ancient Chinese philosopher traditionally regarded as the founder of Taoism and the author of the Tao Te Ching, one of the most translated works in world literature.","According to tradition, Laozi served as the keeper of the archives at the royal court of Zhou. His historical existence is debated, but his influence is undeniable.","The Tao Te Ching established the philosophical foundation for Taoism, influencing Chinese religion, art, literature, and governance for over two millennia.",[(-530,"Traditionally attributed composition of Tao Te Ching"),(-520,"Legendarily met with Confucius")],[("Tao Te Ching",-500,"Foundational text of Taoism on the nature of existence and the way of harmony")],[("The journey of a thousand miles begins with a single step.","Tao Te Ching")])

p("immanuel-kant","Immanuel Kant","イマヌエル・カント",1724,1804,["de"],["philosophy"],"Immanuel Kant was a German philosopher whose Critique of Pure Reason is one of the most influential works in the history of philosophy. He synthesized rationalism and empiricism.","Kant was born in Königsberg, Prussia, and spent his entire life in the city. He studied at the University of Königsberg and became a professor of logic and metaphysics.","Kant's critical philosophy revolutionized epistemology, ethics, and aesthetics. His categorical imperative became a cornerstone of moral philosophy, and his work shaped all subsequent philosophy.",[(1770,"Appointed professor at Königsberg"),(1781,"Published Critique of Pure Reason"),(1788,"Published Critique of Practical Reason"),(1790,"Published Critique of Judgment")],[("Critique of Pure Reason",1781,"Investigated the limits and possibilities of human knowledge"),("Groundwork of the Metaphysics of Morals",1785,"Introduced the categorical imperative as the basis of moral law")],[("Two things fill the mind with ever new and increasing admiration and awe: the starry heavens above me and the moral law within me.","Critique of Practical Reason, 1788")])

p("georg-wilhelm-friedrich-hegel","Georg Wilhelm Friedrich Hegel","ゲオルク・ヴィルヘルム・フリードリヒ・ヘーゲル",1770,1831,["de"],["philosophy"],"Hegel was a German philosopher who developed a comprehensive philosophical framework based on dialectics. His ideas on history, spirit, and the state profoundly influenced Western philosophy.","Hegel was born in Stuttgart, Württemberg. He studied theology and philosophy at the Tübingen Seminary alongside Schelling and the poet Hölderlin.","Hegel's dialectical method and philosophy of history influenced Marx, existentialism, and critical theory. His concept of the dialectic remains central to philosophy.",[(1807,"Published Phenomenology of Spirit"),(1812,"Published Science of Logic"),(1818,"Appointed professor at the University of Berlin"),(1821,"Published Elements of the Philosophy of Right")],[("Phenomenology of Spirit",1807,"Traces the development of consciousness from sense-certainty to absolute knowledge"),("Science of Logic",1812,"Hegel's comprehensive system of dialectical logic")],[("The owl of Minerva spreads its wings only with the falling of the dusk.","Elements of the Philosophy of Right, 1821")])

p("friedrich-nietzsche","Friedrich Nietzsche","フリードリヒ・ニーチェ",1844,1900,["de"],["philosophy"],"Friedrich Nietzsche was a German philosopher whose radical ideas on morality, religion, and the will to power profoundly influenced 20th-century thought.","Nietzsche was born in Röcken, Prussia. He became professor of classical philology at the University of Basel at the remarkably young age of 24.","Nietzsche's critique of traditional morality, his concept of the Übermensch, and his proclamation of the death of God transformed philosophy, literature, and psychology.",[(1872,"Published The Birth of Tragedy"),(1882,"Published The Gay Science"),(1883,"Published Thus Spoke Zarathustra"),(1886,"Published Beyond Good and Evil"),(1889,"Suffered mental collapse in Turin")],[("Thus Spoke Zarathustra",1883,"Philosophical novel introducing the Übermensch and eternal recurrence"),("Beyond Good and Evil",1886,"Critique of traditional morality and philosophical dogmatism")],[("He who has a why to live can bear almost any how.","Twilight of the Idols, 1889")])

p("baruch-spinoza","Baruch Spinoza","バールーフ・デ・スピノザ",1632,1677,["nl"],["philosophy"],"Baruch Spinoza was a Dutch philosopher of Sephardic Jewish origin whose Ethics is one of the greatest works of Western philosophy. He developed a rationalist metaphysical system equating God with Nature.","Spinoza was born in Amsterdam to a Portuguese-Jewish family. He was excommunicated from the Jewish community at age 23 for his radical philosophical views.","Spinoza's pantheistic philosophy and his defense of intellectual freedom influenced the Enlightenment, German idealism, and modern secular thought. Einstein cited Spinoza's God as his own conception.",[(1656,"Excommunicated from the Jewish community"),(1670,"Published Theological-Political Treatise anonymously"),(1677,"Ethics published posthumously")],[("Ethics",1677,"Systematic philosophical work presented in geometric form, equating God with Nature")],[("I have made a ceaseless effort not to ridicule, not to bewail, not to scorn human actions, but to understand them.","Theological-Political Treatise, 1670")])

p("john-locke","John Locke","ジョン・ロック",1632,1704,["gb"],["philosophy","politics"],"John Locke was an English philosopher and physician regarded as the father of liberalism. His political philosophy profoundly influenced the American and French revolutions.","Locke was born in Wrington, Somerset. He studied at Christ Church, Oxford, and became closely associated with Lord Shaftesbury and the Whig movement.","Locke's theory of natural rights, government by consent, and the tabula rasa profoundly influenced democratic thought, the US Constitution, and modern political philosophy.",[(1689,"Published Two Treatises of Government"),(1689,"Published An Essay Concerning Human Understanding"),(1693,"Published Some Thoughts Concerning Education")],[("Two Treatises of Government",1689,"Foundational work on natural rights, property, and government by consent"),("An Essay Concerning Human Understanding",1689,"Major work arguing the mind begins as a blank slate")],[("No man's knowledge here can go beyond his experience.","An Essay Concerning Human Understanding, 1689")])

p("david-hume","David Hume","デイヴィッド・ヒューム",1711,1776,["gb"],["philosophy"],"David Hume was a Scottish philosopher, historian, and economist who is considered one of the most important figures in Western philosophy. He advanced empiricism and skepticism.","Hume was born in Edinburgh, Scotland. He entered the University of Edinburgh at age 12 and later spent time in France developing his philosophical ideas.","Hume's empiricism and skepticism about causation, induction, and the self profoundly influenced Kant, logical positivism, and cognitive science.",[(1739,"Published A Treatise of Human Nature"),(1748,"Published An Enquiry Concerning Human Understanding"),(1751,"Published An Enquiry Concerning the Principles of Morals"),(1776,"Published Dialogues Concerning Natural Religion posthumously")],[("A Treatise of Human Nature",1739,"Comprehensive empiricist philosophy covering understanding, passions, and morals"),("An Enquiry Concerning Human Understanding",1748,"Refined version of his empiricist epistemology")],[("Reason is, and ought only to be the slave of the passions.","A Treatise of Human Nature, 1739")])

p("jean-jacques-rousseau","Jean-Jacques Rousseau","ジャン＝ジャック・ルソー",1712,1778,["ch","fr"],["philosophy","literature"],"Jean-Jacques Rousseau was a Genevan philosopher and writer whose ideas on education, society, and the social contract profoundly influenced the French Revolution and modern political thought.","Rousseau was born in Geneva. Orphaned young and largely self-educated, he moved to Paris where he became associated with the Encyclopedists.","Rousseau's concept of the social contract, his critique of civilization, and his educational philosophy influenced democratic theory, Romanticism, and modern pedagogy.",[(1750,"Won essay prize from the Academy of Dijon"),(1755,"Published Discourse on Inequality"),(1762,"Published The Social Contract and Emile"),(1770,"Completed Confessions")],[("The Social Contract",1762,"Political philosophy arguing that legitimate authority rests on a social contract"),("Emile",1762,"Revolutionary treatise on education emphasizing natural development")],[("Man is born free, and everywhere he is in chains.","The Social Contract, 1762")])

p("karl-marx","Karl Marx","カール・マルクス",1818,1883,["de","gb"],["philosophy","politics"],"Karl Marx was a German philosopher, economist, and revolutionary socialist whose works on capitalism, class struggle, and historical materialism shaped modern political thought and world history.","Marx was born in Trier, Prussia. He studied law and philosophy at the Universities of Bonn and Berlin, where he was influenced by Hegel's philosophy.","Marx's analysis of capitalism, theory of historical materialism, and call for proletarian revolution influenced revolutions worldwide and shaped the political landscape of the 20th century.",[(1848,"Published The Communist Manifesto with Engels"),(1849,"Exiled to London"),(1867,"Published Volume I of Das Kapital"),(1864,"Founded the International Workingmen's Association")],[("Das Kapital",1867,"Comprehensive critique of political economy and capitalism"),("The Communist Manifesto",1848,"Political pamphlet calling for workers' revolution")],[("The philosophers have only interpreted the world in various ways; the point is to change it.","Theses on Feuerbach, 1845")])

p("ludwig-wittgenstein","Ludwig Wittgenstein","ルートヴィヒ・ウィトゲンシュタイン",1889,1951,["at","gb"],["philosophy"],"Ludwig Wittgenstein was an Austrian-British philosopher who made revolutionary contributions to logic, philosophy of language, and philosophy of mind. He is considered one of the greatest philosophers of the 20th century.","Wittgenstein was born in Vienna into one of Europe's wealthiest families. He studied engineering before turning to philosophy under Bertrand Russell at Cambridge.","Wittgenstein's two major works represent two distinct philosophical approaches: the logical atomism of the Tractatus and the language-game theory of the Investigations. Both transformed analytic philosophy.",[(1921,"Published Tractatus Logico-Philosophicus"),(1929,"Returned to Cambridge"),(1939,"Succeeded G.E. Moore as professor at Cambridge"),(1953,"Philosophical Investigations published posthumously")],[("Tractatus Logico-Philosophicus",1921,"Logical analysis of the relationship between language and reality"),("Philosophical Investigations",1953,"Rejected earlier work, introduced language games and family resemblance")],[("Whereof one cannot speak, thereof one must be silent.","Tractatus Logico-Philosophicus, 1921")])

p("jean-paul-sartre","Jean-Paul Sartre","ジャン＝ポール・サルトル",1905,1980,["fr"],["philosophy","literature"],"Jean-Paul Sartre was a French existentialist philosopher, playwright, and novelist. He was one of the leading intellectual figures of the 20th century.","Sartre was born in Paris. He studied at the École Normale Supérieure and taught philosophy before becoming a full-time writer after World War II.","Sartre's existentialism, centered on radical freedom and responsibility, profoundly influenced philosophy, literature, and political activism. He declined the Nobel Prize in Literature in 1964.",[(1938,"Published Nausea"),(1943,"Published Being and Nothingness"),(1945,"Delivered lecture Existentialism Is a Humanism"),(1964,"Declined the Nobel Prize in Literature")],[("Being and Nothingness",1943,"Major work of existentialist philosophy on consciousness, freedom, and bad faith"),("Nausea",1938,"Philosophical novel exploring existential anxiety and contingency")],[("Existence precedes essence.","Existentialism Is a Humanism, 1945")])

p("simone-de-beauvoir","Simone de Beauvoir","シモーヌ・ド・ボーヴォワール",1908,1986,["fr"],["philosophy","literature"],"Simone de Beauvoir was a French existentialist philosopher and feminist writer. Her book The Second Sex is a foundational text of modern feminism.","De Beauvoir was born in Paris to a bourgeois family. She studied philosophy at the Sorbonne and the École Normale Supérieure, where she met Jean-Paul Sartre.","The Second Sex's analysis of women's oppression launched the second wave of feminism. De Beauvoir's existentialist ethics and feminist philosophy transformed social thought.",[(1943,"Published She Came to Stay"),(1949,"Published The Second Sex"),(1954,"Won the Prix Goncourt for The Mandarins"),(1970,"Became active in the women's liberation movement")],[("The Second Sex",1949,"Groundbreaking analysis of women's oppression and the construction of femininity")],[("One is not born, but rather becomes, a woman.","The Second Sex, 1949")])

p("hannah-arendt","Hannah Arendt","ハンナ・アーレント",1906,1975,["de","us"],["philosophy","politics"],"Hannah Arendt was a German-American political theorist whose works on totalitarianism, the nature of power, and the banality of evil are among the most important in 20th-century political thought.","Arendt was born in Hanover, Germany, to a secular Jewish family. She studied under Heidegger and Jaspers before fleeing Nazi Germany in 1933.","Arendt's analysis of totalitarianism, her concept of the banality of evil, and her theory of political action transformed political philosophy and our understanding of modern political phenomena.",[(1933,"Fled Nazi Germany"),(1951,"Published The Origins of Totalitarianism"),(1958,"Published The Human Condition"),(1963,"Published Eichmann in Jerusalem")],[("The Origins of Totalitarianism",1951,"Analysis of Nazism and Stalinism as new forms of political domination"),("Eichmann in Jerusalem",1963,"Report on the trial of Adolf Eichmann, introducing the concept of the banality of evil")],[("The sad truth is that most evil is done by people who never make up their minds to be good or evil.","The Life of the Mind, 1978")])

p("thomas-aquinas","Thomas Aquinas","トマス・アクィナス",1225,1274,["it"],["philosophy"],"Thomas Aquinas was an Italian Dominican friar and philosopher-theologian who synthesized Aristotelian philosophy with Christian theology. He is the most influential philosopher in the Catholic tradition.","Aquinas was born in Roccasecca, Italy, to a noble family. Against his family's wishes, he joined the Dominican order and studied under Albertus Magnus in Cologne and Paris.","Aquinas's Summa Theologica became the definitive work of Catholic philosophy and theology. His synthesis of faith and reason, and his natural law theory, remain influential in philosophy, law, and ethics.",[(1245,"Joined the Dominican order"),(1256,"Became professor at the University of Paris"),(1265,"Began writing Summa Theologica"),(1274,"Died en route to the Council of Lyon")],[("Summa Theologica",1265,"Comprehensive synthesis of Christian theology and Aristotelian philosophy")],[("To one who has faith, no explanation is necessary. To one without faith, no explanation is possible.","Attributed")])

p("augustine-of-hippo","Augustine of Hippo","アウグスティヌス",354,430,["dz"],["philosophy"],  "Augustine of Hippo was a theologian and philosopher who profoundly shaped Western Christianity and philosophy. His Confessions is considered the first Western autobiography.","Augustine was born in Thagaste, Roman North Africa. He lived a dissolute youth before his dramatic conversion to Christianity in 386 AD, influenced by Ambrose of Milan.","Augustine's theology of grace, original sin, and the City of God dominated Western Christian thought for a millennium. His introspective Confessions pioneered autobiography and the philosophy of time.",[(386,"Converted to Christianity in Milan"),(396,"Became Bishop of Hippo"),(397,"Published Confessions"),(413,"Began The City of God"),(430,"Died during the Vandal siege of Hippo")],[("Confessions",397,"Spiritual autobiography and philosophical meditation on memory, time, and God"),("The City of God",426,"Major work of Christian philosophy contrasting the earthly and heavenly cities")],[("Grant me chastity and continence, but not yet.","Confessions, 397")])

p("al-farabi","Al-Farabi","アル＝ファーラービー",872,950,["kz"],["philosophy"],"Al-Farabi was a renowned Islamic philosopher and polymath known as the Second Teacher after Aristotle. He made major contributions to political philosophy, logic, and music theory.","Al-Farabi was born in Farab, in present-day Kazakhstan. He studied in Baghdad, the intellectual center of the Islamic Golden Age.","Al-Farabi's commentaries on Aristotle and Plato preserved and transmitted Greek philosophy to the medieval world. His political philosophy influenced both Islamic and European thought.",[(900,"Moved to Baghdad to study"),(940,"Published The Virtuous City"),(942,"Published The Book of Letters")],[("The Virtuous City",940,"Political philosophy describing the ideal state, influenced by Plato's Republic")],[("The philosopher must also be a statesman and a legislator.","The Virtuous City")])

p("avicenna","Avicenna","イブン・スィーナー",980,1037,["ir"],["philosophy","biology"],"Avicenna (Ibn Sina) was a Persian polymath regarded as one of the most significant thinkers of the Islamic Golden Age. He made major contributions to philosophy, medicine, and science.","Avicenna was born near Bukhara in present-day Uzbekistan. A child prodigy, he had memorized the Quran by age 10 and mastered medicine by 18.","Avicenna's Canon of Medicine was the standard medical textbook in Europe and the Islamic world for centuries. His philosophical works profoundly influenced both Islamic and Scholastic philosophy.",[(1005,"Began writing The Canon of Medicine"),(1020,"Completed The Book of Healing"),(1025,"Published The Canon of Medicine")],[("The Canon of Medicine",1025,"Comprehensive medical encyclopedia used as a textbook for centuries"),("The Book of Healing",1020,"Major philosophical and scientific encyclopedia")],[("The knowledge of anything, since all things have causes, is not acquired or complete unless it is known by its causes.","The Book of Healing")])

p("averroes","Averroes","イブン・ルシュド",1126,1198,["es"],["philosophy"],"Averroes (Ibn Rushd) was an Andalusian-Arab philosopher and jurist who wrote extensive commentaries on Aristotle, earning him the title 'The Commentator' in medieval Europe.","Averroes was born in Córdoba, Al-Andalus. From a family of jurists, he studied law, medicine, and philosophy, becoming chief judge of Córdoba.","Averroes' commentaries on Aristotle preserved and transmitted Greek philosophy to medieval Europe, catalyzing the Scholastic movement. His defense of philosophy's autonomy influenced Aquinas and European thought.",[(1169,"Began writing commentaries on Aristotle"),(1180,"Published The Incoherence of the Incoherence"),(1195,"Exiled from Córdoba for his philosophical views")],[("The Incoherence of the Incoherence",1180,"Defense of Aristotelian philosophy against al-Ghazali's critique")],[("Ignorance leads to fear, fear leads to hate, and hate leads to violence. This is the equation.","Attributed")])

p("zhuangzi","Zhuangzi","荘子",-369,-286,["cn"],["philosophy"],"Zhuangzi was an ancient Chinese philosopher and one of the founders of Taoism. His eponymous book is one of the most important texts in Chinese philosophy.","Little is known about Zhuangzi's life. He is traditionally believed to have lived in the state of Meng during the Warring States period and declined a government position.","Zhuangzi's philosophy of spontaneity, relativism, and harmony with nature profoundly influenced Chinese thought, art, poetry, and Chan/Zen Buddhism.",[(-320,"Composed the inner chapters of the Zhuangzi"),(-300,"Zhuangzi compiled by later followers")],[("Zhuangzi",-300,"Collection of parables and philosophical arguments on the nature of reality and freedom")],[("The fish trap exists because of the fish. Once you've gotten the fish you can forget the trap.","Zhuangzi")])

p("arthur-schopenhauer","Arthur Schopenhauer","アルトゥル・ショーペンハウアー",1788,1860,["de"],["philosophy"],"Arthur Schopenhauer was a German philosopher best known for his work The World as Will and Representation, which characterized the phenomenal world as driven by a blind, purposeless will.","Schopenhauer was born in Danzig to a wealthy merchant family. He studied philosophy at the University of Berlin, where he developed a rivalry with Hegel.","Schopenhauer's pessimistic philosophy and his emphasis on the will influenced Nietzsche, Freud, Wagner, Wittgenstein, and existentialism. He was also one of the first Western philosophers to engage seriously with Eastern thought.",[(1818,"Published The World as Will and Representation"),(1836,"Published On the Will in Nature"),(1851,"Published Parerga and Paralipomena, bringing fame")],[("The World as Will and Representation",1818,"Major work arguing the world is driven by an irrational, purposeless will")],[("All truth passes through three stages: first it is ridiculed, second it is violently opposed, third it is accepted as self-evident.","Attributed")])

p("soren-kierkegaard","Søren Kierkegaard","セーレン・キェルケゴール",1813,1855,["dk"],["philosophy"],"Søren Kierkegaard was a Danish philosopher, theologian, and cultural critic, widely considered the first existentialist philosopher.","Kierkegaard was born in Copenhagen to a wealthy family. He studied theology at the University of Copenhagen and spent most of his life writing in Copenhagen.","Kierkegaard's emphasis on individual existence, subjective truth, and the leap of faith founded existentialism and profoundly influenced 20th-century philosophy, theology, and psychology.",[(1843,"Published Either/Or and Fear and Trembling"),(1844,"Published The Concept of Anxiety"),(1846,"Published Concluding Unscientific Postscript"),(1849,"Published The Sickness Unto Death")],[("Either/Or",1843,"Exploration of aesthetic and ethical modes of existence"),("Fear and Trembling",1843,"Meditation on faith through the story of Abraham and Isaac")],[("Life can only be understood backwards; but it must be lived forwards.","Journals, 1843")])

p("john-stuart-mill","John Stuart Mill","ジョン・スチュアート・ミル",1806,1873,["gb"],["philosophy","politics"],"John Stuart Mill was a British philosopher and political economist who was the most influential English-speaking philosopher of the 19th century. He championed utilitarianism and individual liberty.","Mill was born in London and received an extraordinarily rigorous education from his father, James Mill. He was reading Greek at three and Latin at eight.","Mill's On Liberty remains a classic defense of individual freedom. His utilitarian ethics, feminist advocacy, and political economy profoundly influenced liberal democratic thought.",[(1843,"Published A System of Logic"),(1848,"Published Principles of Political Economy"),(1859,"Published On Liberty"),(1861,"Published Utilitarianism"),(1869,"Published The Subjection of Women")],[("On Liberty",1859,"Classic defense of individual freedom against social and governmental tyranny"),("Utilitarianism",1861,"Systematic defense and refinement of utilitarian moral philosophy")],[("The only purpose for which power can be rightfully exercised over any member of a civilized community, against his will, is to prevent harm to others.","On Liberty, 1859")])

p("voltaire","Voltaire","ヴォルテール",1694,1778,["fr"],["philosophy","literature"],"Voltaire was a French Enlightenment writer, philosopher, and satirist known for his wit, his advocacy of civil liberties, and his criticism of the Catholic Church.","Voltaire was born François-Marie Arouet in Paris. He was educated by Jesuits and became famous for his sharp social commentary, which led to his imprisonment in the Bastille.","Voltaire's advocacy of freedom of speech, separation of church and state, and religious tolerance profoundly influenced the French and American revolutions and modern democratic thought.",[(1718,"Adopted the name Voltaire; premiered Oedipe"),(1726,"Exiled to England for three years"),(1734,"Published Philosophical Letters"),(1759,"Published Candide"),(1764,"Published Philosophical Dictionary")],[("Candide",1759,"Satirical novella critiquing optimism and social injustice"),("Philosophical Letters",1734,"Praise of English liberty that challenged French institutions")],[("I disapprove of what you say, but I will defend to the death your right to say it.","Attributed by Evelyn Beatrice Hall")])

p("montesquieu","Montesquieu","モンテスキュー",1689,1755,["fr"],["philosophy","politics"],"Montesquieu was a French political philosopher whose theory of separation of powers became the foundation of modern constitutional government.","Charles-Louis de Secondat, Baron de Montesquieu, was born near Bordeaux. He inherited a judicial office and devoted himself to political philosophy.","Montesquieu's separation of powers directly influenced the US Constitution and modern democratic governance. His comparative study of governments pioneered political sociology.",[(1721,"Published Persian Letters"),(1734,"Published Considerations on the Romans"),(1748,"Published The Spirit of the Laws")],[("The Spirit of the Laws",1748,"Comparative study of governments advocating separation of legislative, executive, and judicial powers")],[("There is no greater tyranny than that which is perpetrated under the shield of the law and in the name of justice.","The Spirit of the Laws, 1748")])

p("epicurus","Epicurus","エピクロス",-341,-270,["gr"],["philosophy"],"Epicurus was an ancient Greek philosopher who founded Epicureanism, a philosophy advocating the pursuit of modest pleasures, friendship, and freedom from fear as the path to happiness.","Epicurus was born on the island of Samos. He began studying philosophy at age 14 and later founded his school, the Garden, in Athens.","Epicurean philosophy offered a materialist worldview and an ethics based on pleasure and pain that influenced Roman thought, the Scientific Revolution, and modern utilitarian ethics.",[(-306,"Founded the Garden school in Athens"),(-300,"Developed atomic theory of nature")],[("Letter to Menoeceus",-300,"Outline of Epicurean ethics and the pursuit of ataraxia")],[("Death does not concern us, because as long as we exist, death is not here. And when it does come, we no longer exist.","Letter to Menoeceus")])

p("marcus-aurelius","Marcus Aurelius","マルクス・アウレリウス",121,180,["it"],["philosophy","politics"],"Marcus Aurelius was a Roman emperor and Stoic philosopher whose Meditations is one of the greatest works of Stoic philosophy, written as private reflections during military campaigns.","Marcus Aurelius was born in Rome to a prominent family. Adopted by Emperor Antoninus Pius, he received an excellent education including training in Stoic philosophy.","The Meditations remains one of the most widely read philosophical works, offering timeless guidance on duty, virtue, and resilience. Marcus Aurelius is considered the last of the Five Good Emperors.",[(138,"Adopted by Emperor Antoninus Pius"),(161,"Became Roman Emperor"),(167,"Began writing Meditations during military campaigns"),(180,"Died in Vindobona during the Marcomannic Wars")],[("Meditations",170,"Private philosophical reflections on Stoic ethics, duty, and human nature")],[("The happiness of your life depends upon the quality of your thoughts.","Meditations")])

p("francis-bacon","Francis Bacon","フランシス・ベーコン",1561,1626,["gb"],["philosophy"],"Francis Bacon was an English philosopher and statesman who developed the empirical method and is considered the father of empiricism and the scientific method.","Bacon was born in London to a prominent political family. He studied at Trinity College, Cambridge, and pursued a career in law and politics alongside his philosophical work.","Bacon's advocacy of inductive reasoning and empirical observation laid the philosophical groundwork for modern science. His vision of organized scientific research anticipated modern research institutions.",[(1597,"Published first edition of Essays"),(1605,"Published The Advancement of Learning"),(1620,"Published Novum Organum"),(1623,"Published De Augmentis Scientiarum")],[("Novum Organum",1620,"Introduced the inductive method as an alternative to Aristotelian deduction")],[("Knowledge is power.","Meditationes Sacrae, 1597")])

p("thomas-hobbes","Thomas Hobbes","トマス・ホッブズ",1588,1679,["gb"],["philosophy","politics"],"Thomas Hobbes was an English philosopher best known for his political philosophy, particularly Leviathan, which argues for a strong sovereign authority to prevent the chaos of the state of nature.","Hobbes was born in Westport, Wiltshire. He studied at the University of Oxford and spent time in Continental Europe, where he met Galileo and Descartes.","Hobbes's social contract theory and his materialist philosophy profoundly influenced political science and modern political thought. Leviathan remains a foundational text of political philosophy.",[(1628,"Translated Thucydides' History"),(1640,"Published The Elements of Law"),(1651,"Published Leviathan"),(1655,"Published De Corpore")],[("Leviathan",1651,"Foundational work arguing for social contract and strong sovereign authority")],[("The life of man, solitary, poor, nasty, brutish, and short.","Leviathan, 1651")])

p("gottfried-herder","Johann Gottfried Herder","ヨハン・ゴットフリート・ヘルダー",1744,1803,["de"],["philosophy","literature"],"Johann Gottfried Herder was a German philosopher, theologian, and literary critic who was a major figure in the Counter-Enlightenment and a founder of cultural nationalism.","Herder was born in Mohrungen, East Prussia. He studied at the University of Königsberg under Kant before becoming a clergyman and writer.","Herder's ideas on cultural identity, folk traditions, and the philosophy of history profoundly influenced Romanticism, nationalism, and modern anthropology.",[(1769,"Published Critical Forests"),(1774,"Published This Too a Philosophy of History"),(1784,"Published Ideas on the Philosophy of the History of Mankind")],[("Ideas on the Philosophy of the History of Mankind",1784,"Comprehensive philosophy of human cultural development")],[("Without inspiration the best powers of the mind remain dormant.","Attributed")])

p("michel-de-montaigne","Michel de Montaigne","ミシェル・ド・モンテーニュ",1533,1592,["fr"],["philosophy","literature"],"Michel de Montaigne was a French philosopher and essayist who popularized the essay as a literary form. His candid explorations of the human condition remain remarkably modern.","Montaigne was born in the Périgord region of France to a wealthy family. He was educated in Latin from infancy and later studied law before retiring to write.","Montaigne's Essays pioneered the personal essay form and influenced Shakespeare, Descartes, Pascal, and Nietzsche. His skeptical humanism and self-examination remain profoundly influential.",[(1571,"Retired to his estate to begin writing"),(1580,"Published first two books of Essais"),(1588,"Published third book of Essais")],[("Essais",1580,"Personal philosophical reflections that created the essay as a literary genre")],[("Que sais-je? (What do I know?)","Essais, 1580")])

p("nagarjuna","Nagarjuna","ナーガールジュナ",150,250,["in"],["philosophy"],"Nagarjuna was an Indian Buddhist philosopher who founded the Madhyamaka school of Mahayana Buddhism. He is widely regarded as the most important Buddhist philosopher after the Buddha himself.","Little is known about Nagarjuna's early life. He is traditionally believed to have been born in South India and to have become a Buddhist monk and scholar at Nalanda.","Nagarjuna's concept of sunyata (emptiness) and his dialectical method profoundly shaped Mahayana Buddhism across East and Central Asia. His philosophy influenced all subsequent Buddhist thought.",[(150,"Born in South India"),(200,"Composed Mulamadhyamakakarika")],[("Mulamadhyamakakarika",200,"Foundational verses of the Middle Way, establishing the Madhyamaka school")],[("Whatever is dependently co-arisen, that is explained to be emptiness.","Mulamadhyamakakarika")])

p("martin-heidegger","Martin Heidegger","マルティン・ハイデッガー",1889,1976,["de"],["philosophy"],"Martin Heidegger was a German philosopher whose exploration of the question of Being is one of the most significant contributions to 20th-century philosophy.","Heidegger was born in Meßkirch, Baden. He studied theology and philosophy at the University of Freiburg and became Edmund Husserl's assistant.","Heidegger's Being and Time fundamentally reoriented philosophy toward the question of existence. His influence extends through existentialism, hermeneutics, postmodernism, and environmental philosophy.",[(1927,"Published Being and Time"),(1933,"Became rector of the University of Freiburg under the Nazi regime"),(1946,"Banned from teaching by denazification authorities"),(1951,"Resumed teaching and lecturing")],[("Being and Time",1927,"Fundamental ontology exploring the meaning of Being through human existence (Dasein)")],[("Language is the house of Being.","Letter on Humanism, 1947")])

p("edmund-husserl","Edmund Husserl","エトムント・フッサール",1859,1938,["de","at"],["philosophy","mathematics"],"Edmund Husserl was a German philosopher who founded phenomenology, the study of structures of consciousness as experienced from the first-person point of view.","Husserl was born in Prossnitz, Moravia. He studied mathematics under Karl Weierstrass in Berlin before turning to philosophy under Franz Brentano.","Husserl's phenomenology became one of the most important philosophical movements of the 20th century, influencing existentialism, hermeneutics, and cognitive science.",[(1891,"Published Philosophy of Arithmetic"),(1900,"Published Logical Investigations"),(1913,"Published Ideas Pertaining to a Pure Phenomenology"),(1929,"Delivered Paris Lectures on Cartesian Meditations")],[("Logical Investigations",1900,"Foundational work establishing phenomenology as a philosophical method")],[("To the things themselves!","Motto of phenomenology, Logical Investigations")])

p("michel-foucault","Michel Foucault","ミシェル・フーコー",1926,1984,["fr"],["philosophy"],"Michel Foucault was a French philosopher and social theorist whose analyses of power, knowledge, and discourse transformed the humanities and social sciences.","Foucault was born in Poitiers, France. He studied at the École Normale Supérieure and earned degrees in philosophy and psychology.","Foucault's analyses of how power operates through institutions, discourse, and knowledge reshaped sociology, cultural studies, literary theory, and political thought.",[(1961,"Published Madness and Civilization"),(1966,"Published The Order of Things"),(1975,"Published Discipline and Punish"),(1976,"Published first volume of The History of Sexuality")],[("Discipline and Punish",1975,"Analysis of the modern penal system and the relationship between power and knowledge"),("The Order of Things",1966,"Archaeology of the human sciences and systems of knowledge")],[("Where there is power, there is resistance.","The History of Sexuality, 1976")])

p("jacques-derrida","Jacques Derrida","ジャック・デリダ",1930,2004,["dz","fr"],["philosophy"],"Jacques Derrida was a French philosopher who developed deconstruction, a method of critical analysis that examines how meaning is constructed and destabilized in texts.","Derrida was born in El Biar, French Algeria, to a Sephardic Jewish family. He studied at the École Normale Supérieure in Paris and taught philosophy in France and the United States.","Derrida's deconstruction profoundly influenced literary criticism, philosophy, architecture, and cultural studies. His questioning of binary oppositions reshaped postmodern thought.",[(1967,"Published Of Grammatology, Writing and Difference, and Speech and Phenomena"),(1972,"Published Margins of Philosophy"),(1993,"Published Specters of Marx")],[("Of Grammatology",1967,"Foundational text of deconstruction challenging the primacy of speech over writing")],[("There is nothing outside the text.","Of Grammatology, 1967")])

p("seneca","Seneca","セネカ",-4,65,["it"],["philosophy","literature"],"Seneca was a Roman Stoic philosopher, statesman, and dramatist who served as advisor to Emperor Nero. His letters and essays are major works of Stoic ethics.","Seneca was born in Corduba, Hispania. He was educated in Rome in rhetoric and philosophy and rose to political prominence as tutor and advisor to the young Emperor Nero.","Seneca's Letters and essays made Stoic philosophy accessible and practical. His emphasis on virtue, self-discipline, and the brevity of life continues to resonate widely.",[(41,"Exiled to Corsica by Emperor Claudius"),(49,"Recalled to tutor the young Nero"),(54,"Became chief advisor to Emperor Nero"),(65,"Forced to commit suicide by Nero")],[("Letters to Lucilius",64,"Collection of 124 philosophical letters on Stoic ethics and practical wisdom"),("On the Shortness of Life",49,"Essay arguing that life is long enough if lived wisely")],[("It is not that we have a short time to live, but that we waste a great deal of it.","On the Shortness of Life")])

p("epictetus","Epictetus","エピクテトス",50,135,["gr","it"],["philosophy"],"Epictetus was a Greek Stoic philosopher who was born a slave and became one of the most influential teachers of Stoic ethics in the Roman Empire.","Epictetus was born a slave in Hierapolis, Phrygia. After gaining his freedom, he studied under the Stoic philosopher Musonius Rufus and later founded his own school in Nicopolis.","Epictetus's Discourses and Enchiridion became foundational Stoic texts emphasizing that virtue and happiness depend on what is within our control. His influence extends to cognitive behavioral therapy.",[(70,"Studied under Musonius Rufus"),(89,"Banished from Rome by Domitian"),(90,"Founded school in Nicopolis"),(135,"Discourses recorded by student Arrian")],[("Discourses",108,"Record of Epictetus's philosophical teachings by his student Arrian"),("Enchiridion",108,"Handbook summarizing Epictetus's key Stoic teachings")],[("It's not what happens to you, but how you react to it that matters.","Attributed")])

p("mencius","Mencius","孟子",-372,-289,["cn"],["philosophy"],"Mencius was a Chinese Confucian philosopher often described as the second sage of Confucianism. He argued that human nature is innately good and that rulers must govern benevolently.","Mencius was born in the state of Zou, near Confucius's home state of Lu. He studied under a student of Confucius's grandson and traveled among the Warring States rulers.","Mencius's arguments for innate human goodness and benevolent government became central to Confucian thought and East Asian political philosophy.",[(-320,"Traveled to the state of Qi"),(-310,"Served as advisor to King Xuan of Qi"),(-300,"Retired from public life to teach")],[("Mencius",-300,"Collection of conversations and teachings on Confucian ethics and political philosophy")],[("The people are the most important element in a nation; the spirits of the land come next; the sovereign counts for least.","Mencius")])

p("al-ghazali","Al-Ghazali","アル＝ガザーリー",1058,1111,["ir"],["philosophy"],"Al-Ghazali was a Persian theologian, philosopher, and mystic who profoundly influenced Islamic thought. His critique of philosophy and embrace of Sufism reshaped the Islamic intellectual tradition.","Al-Ghazali was born in Tus, Persia. He became a professor at the Nizamiyyah university in Baghdad before experiencing a spiritual crisis that led him to abandon his position for Sufi practice.","Al-Ghazali's The Incoherence of the Philosophers challenged rationalist philosophy in Islam, while his Revival of the Religious Sciences synthesized orthodox theology with Sufi mysticism.",[(1091,"Appointed professor at the Nizamiyyah in Baghdad"),(1095,"Experienced spiritual crisis and left Baghdad"),(1095,"Published The Incoherence of the Philosophers"),(1106,"Published The Revival of the Religious Sciences")],[("The Revival of the Religious Sciences",1106,"Comprehensive synthesis of Islamic theology, jurisprudence, and Sufi mysticism"),("The Incoherence of the Philosophers",1095,"Critique of Aristotelian and Neoplatonic philosophy in the Islamic world")],[("Knowledge without action is wastefulness, and action without knowledge is foolishness.","The Revival of the Religious Sciences")])

p("john-rawls","John Rawls","ジョン・ロールズ",1921,2002,["us"],["philosophy","politics"],"John Rawls was an American political philosopher whose A Theory of Justice is one of the most influential works of political philosophy in the 20th century.","Rawls was born in Baltimore, Maryland. He served in the Pacific during World War II and later earned his PhD from Princeton, eventually becoming professor at Harvard.","Rawls's theory of justice as fairness, his veil of ignorance thought experiment, and his concept of the original position revived social contract theory and shaped contemporary liberal political philosophy.",[(1951,"Earned PhD from Princeton"),(1962,"Joined Harvard University faculty"),(1971,"Published A Theory of Justice"),(1993,"Published Political Liberalism")],[("A Theory of Justice",1971,"Revived social contract theory through the concepts of the original position and the veil of ignorance")],[("Justice is the first virtue of social institutions, as truth is of systems of thought.","A Theory of Justice, 1971")])

p("noam-chomsky","Noam Chomsky","ノーム・チョムスキー",1928,None,["us"],["philosophy"],  "Noam Chomsky is an American linguist, philosopher, and political activist who revolutionized linguistics with his theory of generative grammar. He is also one of the most prominent public intellectuals.","Chomsky was born in Philadelphia to a family of Jewish immigrants. He studied linguistics and philosophy at the University of Pennsylvania and has spent most of his career at MIT.","Chomsky's theory of universal grammar transformed linguistics and cognitive science. His political writings on media, foreign policy, and power have made him one of the most cited scholars alive.",[(1955,"Joined MIT faculty"),(1957,"Published Syntactic Structures"),(1965,"Published Aspects of the Theory of Syntax"),(1967,"Published The Responsibility of Intellectuals"),(1988,"Published Manufacturing Consent")],[("Syntactic Structures",1957,"Revolutionary work proposing transformational generative grammar"),("Manufacturing Consent",1988,"Analysis of media propaganda in democratic societies")],[("If we don't believe in freedom of expression for people we despise, we don't believe in it at all.","BBC interview, 1992")])

p("simone-weil","Simone Weil","シモーヌ・ヴェイユ",1909,1943,["fr"],["philosophy"],"Simone Weil was a French philosopher, mystic, and political activist whose writings on attention, affliction, and grace are among the most profound of the 20th century.","Weil was born in Paris to a secular Jewish family. She studied at the École Normale Supérieure and taught philosophy while engaging in labor activism and the Spanish Civil War.","Weil's philosophical writings on attention, the relationship between affliction and grace, and the need for roots in community have influenced theology, ethics, and political thought. She died at 34.",[(1931,"Began teaching philosophy"),(1934,"Worked in Renault factory to experience worker conditions"),(1936,"Joined the Spanish Civil War briefly"),(1943,"Published Gravity and Grace posthumously")],[("Gravity and Grace",1947,"Posthumous collection of aphorisms on attention, affliction, and the sacred"),("The Need for Roots",1949,"Philosophical work on human obligation and community")],[("Attention is the rarest and purest form of generosity.","First and Last Notebooks")])

p("giordano-bruno","Giordano Bruno","ジョルダーノ・ブルーノ",1548,1600,["it"],["philosophy","astronomy"],"Giordano Bruno was an Italian philosopher and cosmological theorist who proposed that the universe is infinite and contains many worlds. He was burned at the stake for heresy.","Bruno was born in Nola, near Naples. He entered the Dominican order but fled after developing unorthodox views, wandering through Europe for years.","Bruno's vision of an infinite universe with innumerable worlds anticipated modern cosmology. His martyrdom for free thought made him a symbol of intellectual freedom.",[(1576,"Fled the Dominican order"),(1584,"Published On the Infinite Universe and Worlds"),(1591,"Arrested by the Inquisition in Venice"),(1600,"Burned at the stake in Rome for heresy")],[("On the Infinite Universe and Worlds",1584,"Proposed an infinite universe containing innumerable inhabited worlds")],[("Perhaps your fear in passing judgment on me is greater than mine in receiving it.","Attributed, to his judges")])

p("thomas-more","Thomas More","トマス・モア",1478,1535,["gb"],["philosophy","politics"],"Thomas More was an English lawyer, philosopher, and statesman who served as Lord Chancellor under Henry VIII. His Utopia described an ideal society on a fictional island.","More was born in London and studied law at Lincoln's Inn. He rose through political ranks while maintaining his humanist scholarship and friendship with Erasmus.","More's Utopia coined a word and genre for imagined ideal societies. His martyrdom for refusing to accept Henry VIII's supremacy over the Church made him a saint of the Catholic Church.",[(1516,"Published Utopia"),(1529,"Became Lord Chancellor of England"),(1534,"Imprisoned for refusing the Oath of Supremacy"),(1535,"Executed for treason")],[("Utopia",1516,"Description of an ideal society challenging European social and political norms")],[("I die the King's good servant, but God's first.","Attributed, on the scaffold")])

p("erasmus","Desiderius Erasmus","デジデリウス・エラスムス",1466,1536,["nl"],["philosophy","literature"],"Desiderius Erasmus was a Dutch Renaissance humanist, Catholic priest, and theologian. He was the most famous scholar of his time and a leading figure of Christian humanism.","Erasmus was born in Rotterdam. Orphaned young, he entered a monastery before traveling throughout Europe, studying at Paris and Cambridge, and building a vast network of scholarly correspondents.","Erasmus's satirical works and new translations of the Bible promoted educational reform and religious tolerance. His humanism profoundly influenced the Reformation and the development of European intellectual culture.",[(1500,"Published Adages"),(1509,"Published The Praise of Folly"),(1516,"Published Greek New Testament"),(1524,"Published On Free Will against Luther")],[("The Praise of Folly",1509,"Satirical work criticizing the corruption of the Church and intellectual pretensions"),("Greek New Testament",1516,"Critical edition that became the basis for vernacular Bible translations")],[("In the land of the blind, the one-eyed man is king.","Adages, 1500")])

p("maimonides","Maimonides","マイモニデス",1138,1204,["es","eg"],["philosophy"],"Maimonides (Moses ben Maimon) was a medieval Jewish philosopher, physician, and rabbi who is considered the greatest Jewish philosopher of the Middle Ages.","Maimonides was born in Córdoba, Al-Andalus. His family fled the Almohad persecution and eventually settled in Egypt, where he became the leader of the Jewish community and court physician.","Maimonides' Guide for the Perplexed reconciled Aristotelian philosophy with Jewish theology, influencing both Jewish and Christian Scholastic thought. His Mishneh Torah systematized Jewish law.",[(1168,"Completed Commentary on the Mishnah"),(1178,"Completed the Mishneh Torah"),(1190,"Published The Guide for the Perplexed")],[("The Guide for the Perplexed",1190,"Philosophical work reconciling Aristotelian philosophy with Jewish theology"),("Mishneh Torah",1178,"Comprehensive code of Jewish law")],[("Give a man a fish and you feed him for a day; teach a man to fish and you feed him for a lifetime.","Attributed")])

p("albert-camus","Albert Camus","アルベール・カミュ",1913,1960,["dz","fr"],["philosophy","literature"],"Albert Camus was a French-Algerian philosopher and author who explored absurdism, the conflict between human desire for meaning and the universe's indifference.","Camus was born in Mondovi, French Algeria, to a poor family. He studied philosophy at the University of Algiers and became a journalist and writer.","Camus' philosophy of the absurd and his literary works profoundly influenced existentialism and postwar thought. He received the Nobel Prize in Literature in 1957.",[(1942,"Published The Stranger and The Myth of Sisyphus"),(1947,"Published The Plague"),(1951,"Published The Rebel"),(1957,"Awarded the Nobel Prize in Literature")],[("The Myth of Sisyphus",1942,"Philosophical essay on absurdism and the meaning of life"),("The Stranger",1942,"Novel exploring absurdism through a detached protagonist")],[("One must imagine Sisyphus happy.","The Myth of Sisyphus, 1942")])

p("william-james","William James","ウィリアム・ジェームズ",1842,1910,["us"],["philosophy"],  "William James was an American philosopher and psychologist who was a leading figure in pragmatism and the father of American psychology.","James was born in New York City to a wealthy and intellectual family. He studied medicine at Harvard and later became professor of philosophy and psychology there.","James's pragmatism redefined truth in terms of practical consequences. His Principles of Psychology established psychology as a modern science and his philosophy influenced Dewey, Russell, and Wittgenstein.",[(1890,"Published The Principles of Psychology"),(1897,"Published The Will to Believe"),(1902,"Published The Varieties of Religious Experience"),(1907,"Published Pragmatism")],[("The Principles of Psychology",1890,"Foundational textbook establishing psychology as an empirical science"),("Pragmatism",1907,"Major philosophical work defining truth in terms of practical consequences")],[("Act as if what you do makes a difference. It does.","Attributed")])

p("mary-wollstonecraft","Mary Wollstonecraft","メアリ・ウルストンクラフト",1759,1797,["gb"],["philosophy","politics"],"Mary Wollstonecraft was a British writer and philosopher who is considered the founder of feminist philosophy. Her Vindication of the Rights of Woman argued for women's equality.","Wollstonecraft was born in London to a family of declining means. Largely self-educated, she worked as a governess and teacher before becoming a writer and political commentator.","Wollstonecraft's Vindication of the Rights of Woman is a foundational text of feminism. Her arguments for women's education and equality influenced the suffragist movements and modern gender equality.",[(1787,"Published Thoughts on the Education of Daughters"),(1790,"Published A Vindication of the Rights of Men"),(1792,"Published A Vindication of the Rights of Woman"),(1797,"Died shortly after giving birth to Mary Shelley")],[("A Vindication of the Rights of Woman",1792,"Groundbreaking argument for women's equality and access to education")],[("I do not wish women to have power over men, but over themselves.","A Vindication of the Rights of Woman, 1792")])

p("john-dewey","John Dewey","ジョン・デューイ",1859,1952,["us"],["philosophy"],"John Dewey was an American philosopher, psychologist, and educational reformer who was one of the founders of pragmatism and functional psychology.","Dewey was born in Burlington, Vermont. He studied at Johns Hopkins University and held positions at Michigan, Chicago, and Columbia University.","Dewey's philosophy of education, emphasizing learning by doing and democratic participation, transformed educational practice worldwide. His pragmatism influenced political and social thought.",[(1896,"Founded the Laboratory School at the University of Chicago"),(1899,"Published The School and Society"),(1916,"Published Democracy and Education"),(1934,"Published Art as Experience")],[("Democracy and Education",1916,"Major work on educational philosophy connecting education with democratic values")],[("Education is not preparation for life; education is life itself.","Attributed")])

p("jiddu-krishnamurti","Jiddu Krishnamurti","ジッドゥ・クリシュナムルティ",1895,1986,["in","us"],["philosophy"],"Jiddu Krishnamurti was an Indian-born philosopher and speaker who rejected all organized religion, nationality, and ideology, advocating self-knowledge through direct observation of the mind.","Krishnamurti was born in Madanapalle, India. He was adopted by the Theosophical Society, who proclaimed him a World Teacher, a role he later repudiated.","Krishnamurti's teachings on freedom from conditioning, the nature of the mind, and the importance of self-inquiry influenced millions worldwide and continue through his educational foundations.",[(1929,"Dissolved the Order of the Star, rejecting the role of World Teacher"),(1933,"Began worldwide talks and discussions"),(1969,"Founded the Krishnamurti Foundation"),(1984,"Addressed the United Nations")],[("Freedom from the Known",1969,"Philosophical work on liberation from psychological conditioning")],[("It is no measure of health to be well adjusted to a profoundly sick society.","Attributed")])

write_people(P)
