#!/usr/bin/env python3
"""Generate writers and literary figures."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from people_ai_helper import person, write_people
P = []
p = lambda *a, **k: P.append(person(*a, **k))

p("william-shakespeare","William Shakespeare","ウィリアム・シェイクスピア",1564,1616,["gb"],["literature"],"William Shakespeare was an English playwright and poet, widely regarded as the greatest writer in the English language. His plays have been translated into every major language and are performed more often than those of any other playwright.","Shakespeare was born in Stratford-upon-Avon. He married Anne Hathaway at 18 and moved to London, where he became an actor and playwright with the Lord Chamberlain's Men.","Shakespeare's works defined the English literary canon and profoundly influenced world literature, theater, and the English language itself. He invented over 1,700 words still in use today.",[(1590,"Began writing plays in London"),(1599,"Globe Theatre built"),(1601,"Wrote Hamlet"),(1611,"Wrote The Tempest, his last major play"),(1616,"Died in Stratford-upon-Avon")],[("Hamlet",1601,"Tragedy exploring themes of revenge, mortality, and madness"),("Romeo and Juliet",1597,"Tragedy of star-crossed lovers that defined romantic literature")],[("All the world's a stage, and all the men and women merely players.","As You Like It")])

p("homer","Homer","ホメロス",-800,-701,["gr"],["literature"],"Homer was an ancient Greek poet traditionally credited as the author of the Iliad and the Odyssey, the foundational works of Western literature.","Almost nothing is known about Homer's life. Ancient traditions describe him as a blind bard from Ionia. Whether he was a single author or represents a tradition remains debated.","The Iliad and Odyssey established the epic tradition and profoundly influenced all subsequent Western literature, philosophy, and art.",[(-750,"Composition of the Iliad"),(-725,"Composition of the Odyssey")],[("Iliad",-750,"Epic poem about the Trojan War and the wrath of Achilles"),("Odyssey",-725,"Epic poem about Odysseus's journey home from the Trojan War")],[("Of all creatures that breathe and move upon the earth, nothing is born that is weaker than man.","Odyssey")])

p("dante-alighieri","Dante Alighieri","ダンテ・アリギエーリ",1265,1321,["it"],["literature"],"Dante Alighieri was an Italian poet whose Divine Comedy is considered one of the greatest works of world literature and the preeminent work of Italian literature.","Dante was born in Florence to a family of moderate wealth. He was deeply involved in Florentine politics and was exiled from the city in 1302, never to return.","The Divine Comedy established Italian as a literary language and profoundly influenced Western literature, theology, and art. Its vision of the afterlife shaped European imagination for centuries.",[(1295,"Entered Florentine politics"),(1302,"Exiled from Florence"),(1308,"Began writing the Divine Comedy"),(1321,"Completed Paradiso shortly before death")],[("Divine Comedy",1320,"Epic poem describing a journey through Hell, Purgatory, and Paradise")],[("In the middle of the journey of our life, I found myself in a dark wood.","Inferno, Canto I")])

p("miguel-de-cervantes","Miguel de Cervantes","ミゲル・デ・セルバンテス",1547,1616,["es"],["literature"],"Miguel de Cervantes was a Spanish novelist, poet, and playwright best known for Don Quixote, which is often considered the first modern novel and one of the greatest works of fiction.","Cervantes was born in Alcalá de Henares. He served as a soldier, was captured by pirates and held as a slave in Algiers for five years before being ransomed.","Don Quixote is considered the first modern novel and one of the most influential works of fiction ever written. Cervantes' blend of comedy and pathos created a new literary form.",[(1571,"Fought at the Battle of Lepanto"),(1575,"Captured and enslaved in Algiers"),(1605,"Published Part I of Don Quixote"),(1615,"Published Part II of Don Quixote")],[("Don Quixote",1605,"Novel about a man who loses his sanity reading chivalric romances and sets out as a knight-errant")],[("Too much sanity may be madness — and maddest of all: to see life as it is, and not as it should be!","Don Quixote")])

p("leo-tolstoy","Leo Tolstoy","レフ・トルストイ",1828,1910,["ru"],["literature","philosophy"],"Leo Tolstoy was a Russian novelist widely regarded as one of the greatest writers of all time. War and Peace and Anna Karenina are considered pinnacles of realist fiction.","Tolstoy was born into an aristocratic Russian family at Yasnaya Polyana. He studied at Kazan University, served in the army, and traveled in Europe before devoting himself to writing.","Tolstoy's novels set the standard for realist fiction. His later philosophical and religious works on nonviolent resistance influenced Gandhi, Martin Luther King Jr., and peace movements worldwide.",[(1852,"Published Childhood, his first novel"),(1865,"Began publishing War and Peace"),(1877,"Published Anna Karenina"),(1886,"Published The Death of Ivan Ilyich"),(1910,"Left home and died at a railway station")],[("War and Peace",1869,"Epic novel of Russian society during the Napoleonic Wars"),("Anna Karenina",1877,"Novel exploring love, family, and society in Imperial Russia")],[("All happy families are alike; each unhappy family is unhappy in its own way.","Anna Karenina, 1877")])

p("fyodor-dostoevsky","Fyodor Dostoevsky","フョードル・ドストエフスキー",1821,1881,["ru"],["literature","philosophy"],"Fyodor Dostoevsky was a Russian novelist and philosopher whose psychological depth and exploration of the human condition make him one of the greatest novelists in world literature.","Dostoevsky was born in Moscow. He was arrested for political activities, sentenced to death, reprieved at the last moment, and sent to a Siberian labor camp for four years.","Dostoevsky's exploration of free will, suffering, morality, and the human psyche profoundly influenced existentialism, psychology, and modernist literature.",[(1846,"Published Poor Folk"),(1849,"Arrested and sentenced to mock execution"),(1866,"Published Crime and Punishment"),(1880,"Published The Brothers Karamazov")],[("Crime and Punishment",1866,"Novel exploring guilt, redemption, and the psychology of a murderer"),("The Brothers Karamazov",1880,"Philosophical novel on faith, doubt, morality, and free will")],[("The soul is healed by being with children.","Attributed")])

p("jane-austen","Jane Austen","ジェイン・オースティン",1775,1817,["gb"],["literature"],"Jane Austen was an English novelist known for her wit, social commentary, and masterful depiction of British landed gentry. Her novels remain among the most widely read in English literature.","Austen was born in Steventon, Hampshire, to a large family. She began writing as a teenager and lived a quiet life in the English countryside, never marrying.","Austen's novels transformed the English novel through their irony, realism, and psychological depth. Her works pioneered free indirect discourse and influenced countless writers.",[(1811,"Published Sense and Sensibility"),(1813,"Published Pride and Prejudice"),(1814,"Published Mansfield Park"),(1816,"Published Emma")],[("Pride and Prejudice",1813,"Novel of manners exploring love, class, and first impressions"),("Emma",1816,"Novel about a well-meaning but misguided matchmaker")],[("It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.","Pride and Prejudice, 1813")])

p("charles-dickens","Charles Dickens","チャールズ・ディケンズ",1812,1870,["gb"],["literature"],"Charles Dickens was an English novelist and social critic who created some of the world's best-known fictional characters. He is regarded as the greatest novelist of the Victorian era.","Dickens was born in Portsmouth. His father's imprisonment for debt forced young Charles to work in a factory, an experience that profoundly shaped his social conscience and writing.","Dickens's serialized novels reached massive audiences and raised awareness of social injustice. His characters and stories have become part of Western cultural consciousness.",[(1836,"Published The Pickwick Papers"),(1843,"Published A Christmas Carol"),(1849,"Published David Copperfield"),(1859,"Published A Tale of Two Cities"),(1861,"Published Great Expectations")],[("A Tale of Two Cities",1859,"Historical novel set during the French Revolution"),("A Christmas Carol",1843,"Novella about redemption that transformed Christmas traditions")],[("It was the best of times, it was the worst of times.","A Tale of Two Cities, 1859")])

p("mark-twain","Mark Twain","マーク・トウェイン",1835,1910,["us"],["literature"],"Mark Twain was an American writer, humorist, and lecturer, often called the father of American literature. His Adventures of Huckleberry Finn is considered the Great American Novel.","Samuel Clemens was born in Florida, Missouri. He grew up in Hannibal on the Mississippi River, which inspired much of his writing. He worked as a riverboat pilot before becoming a writer.","Twain's use of vernacular English and his satirical wit transformed American literature. Hemingway said all modern American literature comes from Huckleberry Finn.",[(1865,"Published The Celebrated Jumping Frog of Calaveras County"),(1876,"Published The Adventures of Tom Sawyer"),(1884,"Published Adventures of Huckleberry Finn")],[("Adventures of Huckleberry Finn",1884,"Novel exploring racism and freedom through a boy's journey down the Mississippi")],[("The secret of getting ahead is getting started.","Attributed")])

p("victor-hugo","Victor Hugo","ヴィクトル・ユーゴー",1802,1885,["fr"],["literature","politics"],"Victor Hugo was a French poet, novelist, and dramatist who was the most important of the French Romantic writers. Les Misérables and The Hunchback of Notre-Dame are among the most widely read novels in world literature.","Hugo was born in Besançon, France. He showed early literary talent and was already a celebrated poet in his twenties.","Hugo's novels championed social justice and the dignity of the poor. His political activism for democracy and against capital punishment made him a towering figure in French history.",[(1831,"Published The Hunchback of Notre-Dame"),(1841,"Elected to the Académie française"),(1851,"Exiled for opposing Napoleon III"),(1862,"Published Les Misérables"),(1870,"Returned to France after 19 years of exile")],[("Les Misérables",1862,"Epic novel of social injustice, redemption, and revolution in 19th-century France"),("The Hunchback of Notre-Dame",1831,"Novel set in medieval Paris exploring beauty, cruelty, and justice")],[("Even the darkest night will end and the sun will rise.","Les Misérables, 1862")])

p("franz-kafka","Franz Kafka","フランツ・カフカ",1883,1924,["cz","at"],["literature"],"Franz Kafka was a German-speaking Bohemian novelist whose surreal and nightmarish works explore alienation, bureaucracy, and existential anxiety. The word 'Kafkaesque' derives from his vision.","Kafka was born in Prague to a middle-class Jewish family. He studied law and worked in insurance while writing in his spare time, publishing little during his lifetime.","Kafka's works became defining texts of 20th-century literature. His exploration of absurdity, powerlessness, and alienation influenced existentialism, magical realism, and postmodern literature.",[(1912,"Wrote The Judgment and began The Metamorphosis"),(1915,"Published The Metamorphosis"),(1920,"Published short story collections"),(1924,"Died of tuberculosis; asked Max Brod to burn his manuscripts")],[("The Metamorphosis",1915,"Novella about a man who wakes up transformed into a giant insect"),("The Trial",1925,"Posthumous novel about a man prosecuted by an inaccessible authority")],[("A book must be the axe for the frozen sea within us.","Letter to Oskar Pollak, 1904")])

p("virginia-woolf","Virginia Woolf","ヴァージニア・ウルフ",1882,1941,["gb"],["literature"],"Virginia Woolf was an English writer and modernist who pioneered the use of stream of consciousness in fiction. She is considered one of the most important authors of the 20th century.","Woolf was born in London to a prominent literary family. She was educated at home and became central to the Bloomsbury Group of intellectuals and artists.","Woolf's innovations in narrative technique, particularly stream of consciousness, transformed the novel. Her feminist essays, especially A Room of One's Own, remain foundational texts.",[(1915,"Published The Voyage Out"),(1925,"Published Mrs Dalloway"),(1927,"Published To the Lighthouse"),(1929,"Published A Room of One's Own"),(1941,"Died by suicide")],[("Mrs Dalloway",1925,"Modernist novel following a day in the life of a London socialite"),("A Room of One's Own",1929,"Extended essay on women and fiction arguing for creative and financial independence")],[("A woman must have money and a room of her own if she is to write fiction.","A Room of One's Own, 1929")])

p("gabriel-garcia-marquez","Gabriel García Márquez","ガブリエル・ガルシア＝マルケス",1927,2014,["co"],["literature"],"Gabriel García Márquez was a Colombian novelist and Nobel laureate who was the foremost practitioner of magical realism. One Hundred Years of Solitude is one of the most significant novels of the 20th century.","García Márquez was born in Aracataca, Colombia. Raised by his grandparents, he studied law before becoming a journalist and writer.","García Márquez's magical realism transformed world literature and brought Latin American fiction to global prominence. One Hundred Years of Solitude has sold over 50 million copies.",[(1955,"Published Leaf Storm"),(1967,"Published One Hundred Years of Solitude"),(1981,"Published Chronicle of a Death Foretold"),(1982,"Awarded the Nobel Prize in Literature"),(1985,"Published Love in the Time of Cholera")],[("One Hundred Years of Solitude",1967,"Magical realist novel spanning seven generations of the Buendía family")],[("It is not true that people stop pursuing dreams because they grow old, they grow old because they stop pursuing dreams.","Attributed")])

p("jorge-luis-borges","Jorge Luis Borges","ホルヘ・ルイス・ボルヘス",1899,1986,["ar"],["literature"],"Jorge Luis Borges was an Argentine short-story writer, poet, and essayist whose labyrinthine fictions exploring infinity, mirrors, and identity are among the most original in world literature.","Borges was born in Buenos Aires. He spent his youth in Switzerland and Spain before returning to Argentina, where he worked as a librarian and began publishing stories.","Borges's short stories anticipated postmodernism and hypertext. His influence on world literature is immense, inspiring writers from Umberto Eco to Salman Rushdie.",[(1923,"Published first poetry collection Fervor de Buenos Aires"),(1941,"Published The Garden of Forking Paths"),(1944,"Published Ficciones"),(1961,"Shared the International Publishers' Prize with Samuel Beckett")],[("Ficciones",1944,"Collection of short stories exploring labyrinths, infinite libraries, and alternate realities")],[("I have always imagined that Paradise will be a kind of library.","Attributed")])

p("rabindranath-tagore","Rabindranath Tagore","ラビンドラナート・タゴール",1861,1941,["in"],["literature"],"Rabindranath Tagore was an Indian poet, writer, and philosopher who became the first non-European to win the Nobel Prize in Literature. He is the author of the national anthems of India and Bangladesh.","Tagore was born in Calcutta to a prominent Bengali family. He began writing poetry at age eight and published his first collection at sixteen.","Tagore modernized Bengali literature and introduced Indian culture to the West. His poetry, music, and educational philosophy influenced Indian independence and global literary culture.",[(1901,"Founded the Santiniketan school"),(1910,"Published Gitanjali in Bengali"),(1912,"Published English Gitanjali"),(1913,"Awarded the Nobel Prize in Literature"),(1921,"Founded Visva-Bharati University")],[("Gitanjali",1912,"Collection of spiritual poems that won the Nobel Prize")],[("Where the mind is without fear and the head is held high.","Gitanjali, 1912")])

p("murasaki-shikibu","Murasaki Shikibu","紫式部",978,1014,["jp"],["literature"],"Murasaki Shikibu was a Japanese novelist, poet, and lady-in-waiting at the Imperial court. She is best known as the author of The Tale of Genji, often considered the world's first novel.","Murasaki was born into a minor branch of the Fujiwara clan. She served at the court of Empress Shōshi and is believed to have written her masterwork there.","The Tale of Genji is widely considered the world's first novel and a masterpiece of Japanese literature. It profoundly influenced Japanese aesthetics, poetry, and narrative art.",[(1000,"Began writing The Tale of Genji"),(1005,"Entered service at the Imperial court"),(1010,"Completed The Tale of Genji"),(1010,"Wrote the Murasaki Shikibu Diary")],[("The Tale of Genji",1010,"Considered the world's first novel, chronicling the life of Prince Genji")],[("In this world nothing lasts forever.","The Tale of Genji")])

p("li-bai","Li Bai","李白",701,762,["cn"],["literature"],"Li Bai was a Chinese poet of the Tang dynasty, regarded as one of the two greatest poets in Chinese literary history alongside Du Fu. His romantic, imaginative poetry celebrates nature, friendship, and wine.","Li Bai was born in Central Asia and grew up in Sichuan. He traveled widely, gained fame as a poet, and briefly served at the court of Emperor Xuanzong.","Li Bai's poetry, combining spontaneity with classical mastery, represents the pinnacle of Tang dynasty verse. His works remain among the most beloved in the Chinese literary canon.",[(725,"Began extensive travels throughout China"),(742,"Summoned to the Tang court by Emperor Xuanzong"),(744,"Left the court and resumed wandering"),(762,"Died in Dangtu, Anhui province")],[("Collected Works",750,"Over 1,000 poems covering themes of nature, friendship, wine, and immortality")],[("We sit together, the mountain and me, until only the mountain remains.","Attributed")])

p("du-fu","Du Fu","杜甫",712,770,["cn"],["literature"],"Du Fu was a Chinese poet of the Tang dynasty, known as the Poet-Sage. His socially conscious poetry is considered among the greatest in the Chinese literary tradition.","Du Fu was born into a scholar-official family. He spent years attempting to enter government service and later suffered greatly during the An Lushan Rebellion.","Du Fu's poetry documented the suffering of ordinary people during war and famine with unprecedented compassion and realism. He is revered as China's greatest realist poet.",[(735,"Began travels throughout China"),(755,"Witnessed the An Lushan Rebellion"),(759,"Moved to Chengdu and built the Thatched Cottage"),(770,"Died while traveling")],[("Collected Poems",770,"Approximately 1,500 poems chronicling Tang dynasty life and the impact of war")],[("The nation is broken, though hills and rivers remain.","Spring View")])

p("rumi","Rumi","ルーミー",1207,1273,["af","tr"],["literature","philosophy"],"Rumi was a 13th-century Persian poet, Sufi mystic, and Islamic scholar whose poetry of divine love is among the most widely read in the world. He is the best-selling poet in the United States.","Rumi was born in Balkh, in present-day Afghanistan. His family fled the Mongol invasions and settled in Konya, in present-day Turkey, where Rumi became a scholar and teacher.","Rumi's mystical poetry transcends cultural and religious boundaries. The Masnavi is considered one of the greatest poems in the Persian language, and his works continue to inspire millions worldwide.",[(1244,"Met the wandering dervish Shams-i Tabrizi, transforming his life"),(1248,"Began composing the Diwan-e Shams-e Tabrizi"),(1258,"Began composing the Masnavi"),(1273,"Died in Konya; his funeral attended by people of all faiths")],[("Masnavi",1258,"Epic spiritual poem of 25,000 verses exploring divine love and mystical truth"),("Diwan-e Shams-e Tabrizi",1248,"Collection of lyric poems dedicated to his spiritual mentor Shams")],[("The wound is the place where the Light enters you.","Attributed")])

p("ernest-hemingway","Ernest Hemingway","アーネスト・ヘミングウェイ",1899,1961,["us"],["literature"],"Ernest Hemingway was an American novelist and journalist whose spare, understated prose style influenced 20th-century fiction. He won the Nobel Prize in Literature in 1954.","Hemingway was born in Oak Park, Illinois. He served as an ambulance driver in World War I and later worked as a journalist in Paris, where he joined the expatriate literary community.","Hemingway's iceberg theory of writing — showing only the surface while implying deeper meaning — revolutionized prose fiction. His influence on American literature is immeasurable.",[(1926,"Published The Sun Also Rises"),(1929,"Published A Farewell to Arms"),(1940,"Published For Whom the Bell Tolls"),(1952,"Published The Old Man and the Sea"),(1954,"Awarded the Nobel Prize in Literature")],[("The Old Man and the Sea",1952,"Novella about an aging fisherman's struggle with a giant marlin"),("A Farewell to Arms",1929,"Novel of love and war set during World War I")],[("All you have to do is write one true sentence. Write the truest sentence that you know.","A Moveable Feast, 1964")])

p("edgar-allan-poe","Edgar Allan Poe","エドガー・アラン・ポー",1809,1849,["us"],["literature"],"Edgar Allan Poe was an American writer and poet who pioneered the detective fiction and horror genres. His dark, atmospheric tales and poems remain among the most popular in English literature.","Poe was born in Boston and orphaned young. He was raised by John Allan in Richmond, Virginia, and had a troubled life marked by poverty, alcoholism, and personal loss.","Poe invented the detective story genre and his tales of horror and mystery established American Gothic literature. His literary criticism and theories influenced French Symbolism and world literature.",[(1827,"Published first poetry collection Tamerlane"),(1839,"Published The Fall of the House of Usher"),(1841,"Published The Murders in the Rue Morgue, the first detective story"),(1845,"Published The Raven"),(1849,"Died in Baltimore under mysterious circumstances")],[("The Raven",1845,"Narrative poem about a grieving lover visited by a mysterious raven"),("The Murders in the Rue Morgue",1841,"The first modern detective story, featuring C. Auguste Dupin")],[("All that we see or seem is but a dream within a dream.","A Dream Within a Dream, 1849")])

p("emily-dickinson","Emily Dickinson","エミリー・ディキンソン",1830,1886,["us"],["literature"],"Emily Dickinson was an American poet who wrote nearly 1,800 poems, most published posthumously. Her innovative use of form, punctuation, and imagery made her one of America's greatest poets.","Dickinson was born in Amherst, Massachusetts, to a prominent family. She became increasingly reclusive, rarely leaving her home, while writing prolifically in secret.","Dickinson's unconventional poetry, with its slant rhyme, dashes, and compressed imagery, anticipated modernist poetry. Her exploration of death, immortality, and nature remains profoundly influential.",[(1858,"Began collecting poems into fascicles"),(1862,"Corresponded with Thomas Wentworth Higginson"),(1886,"Died; sister Lavinia discovered nearly 1,800 poems"),(1890,"First collection published posthumously")],[("Collected Poems",1890,"Nearly 1,800 poems exploring death, nature, love, and immortality")],[("Because I could not stop for Death, He kindly stopped for me.","Because I could not stop for Death")])

p("walt-whitman","Walt Whitman","ウォルト・ホイットマン",1819,1892,["us"],["literature"],"Walt Whitman was an American poet whose Leaves of Grass is a landmark in American literature. His free verse and celebration of democracy, nature, and the body revolutionized poetry.","Whitman was born in West Hills, New York. He worked as a journalist, teacher, and government clerk, and volunteered as a nurse during the Civil War.","Whitman's free verse broke from traditional poetic forms and his celebration of the self, democracy, and physical experience opened new possibilities for poetry worldwide.",[(1855,"Self-published the first edition of Leaves of Grass"),(1862,"Volunteered as a Civil War nurse"),(1865,"Published Drum-Taps and O Captain! My Captain!"),(1891,"Published the final deathbed edition of Leaves of Grass")],[("Leaves of Grass",1855,"Revolutionary poetry collection celebrating democracy, nature, and the human body")],[("I am large, I contain multitudes.","Song of Myself, Leaves of Grass")])

p("johann-wolfgang-von-goethe","Johann Wolfgang von Goethe","ヨハン・ヴォルフガング・フォン・ゲーテ",1749,1832,["de"],["literature","philosophy"],"Goethe was a German writer and polymath whose works span poetry, drama, literature, philosophy, and science. He is considered the greatest German literary figure.","Goethe was born in Frankfurt am Main to a prosperous family. He studied law at Leipzig and Strasbourg before gaining fame with his novel The Sorrows of Young Werther.","Goethe's Faust is one of the greatest works of Western literature. His influence extends beyond literature to philosophy, science, and art, and he shaped German cultural identity.",[(1774,"Published The Sorrows of Young Werther"),(1775,"Moved to Weimar at the invitation of Duke Karl August"),(1790,"Published Faust, A Fragment"),(1808,"Published Faust Part One"),(1831,"Completed Faust Part Two")],[("Faust",1832,"Two-part dramatic work exploring the limits of human knowledge and desire"),("The Sorrows of Young Werther",1774,"Epistolary novel that ignited the Sturm und Drang movement")],[("Whatever you can do, or dream you can, begin it. Boldness has genius, power, and magic in it.","Attributed")])

p("toni-morrison","Toni Morrison","トニ・モリスン",1931,2019,["us"],["literature"],"Toni Morrison was an American novelist who explored African American identity and history. She won the Nobel Prize in Literature in 1993, the first African American woman to do so.","Morrison was born Chloe Wofford in Lorain, Ohio. She studied at Howard University and Cornell, and worked as an editor at Random House before becoming a full-time writer.","Morrison's novels transformed American literature by centering Black experience with lyrical prose and mythic depth. Her works reshaped the American literary canon.",[(1970,"Published The Bluest Eye"),(1977,"Published Song of Solomon"),(1987,"Published Beloved"),(1993,"Awarded the Nobel Prize in Literature")],[("Beloved",1987,"Novel about the haunting legacy of slavery, based on the true story of Margaret Garner")],[("If there's a book that you want to read, but it hasn't been written yet, then you must write it.","Attributed")])

p("marcel-proust","Marcel Proust","マルセル・プルースト",1871,1922,["fr"],["literature"],"Marcel Proust was a French novelist whose In Search of Lost Time is one of the most celebrated works of fiction in any language, exploring memory, time, and society.","Proust was born in Paris to a wealthy family. Sickly from childhood, he became increasingly reclusive, spending his final years writing in a cork-lined bedroom.","In Search of Lost Time revolutionized the novel through its exploration of involuntary memory, subjective experience, and the passage of time. Its influence on modernist and postmodernist literature is immeasurable.",[(1896,"Published Pleasures and Days"),(1913,"Published Swann's Way"),(1919,"Won the Prix Goncourt for Within a Budding Grove"),(1922,"Died while revising later volumes")],[("In Search of Lost Time",1913,"Seven-volume novel exploring memory, time, art, and Parisian society")],[("The real voyage of discovery consists not in seeking new landscapes, but in having new eyes.","In Search of Lost Time")])

p("james-joyce","James Joyce","ジェイムズ・ジョイス",1882,1941,["ie"],["literature"],"James Joyce was an Irish novelist whose experimental masterpiece Ulysses is considered one of the most important works of modernist literature.","Joyce was born in Dublin to a large Catholic family. He left Ireland in 1904 and spent most of his life in continental Europe, writing about Dublin from abroad.","Joyce's Ulysses and Finnegans Wake pushed the boundaries of language and narrative form. His stream-of-consciousness technique and linguistic experimentation transformed the modern novel.",[(1904,"Left Ireland; began writing Dubliners"),(1914,"Published Dubliners"),(1916,"Published A Portrait of the Artist as a Young Man"),(1922,"Published Ulysses"),(1939,"Published Finnegans Wake")],[("Ulysses",1922,"Modernist novel paralleling Homer's Odyssey through a single day in Dublin"),("Dubliners",1914,"Collection of short stories depicting Irish middle-class life")],[("A man of genius makes no mistakes. His errors are volitional and are the portals of discovery.","Ulysses, 1922")])

p("oscar-wilde","Oscar Wilde","オスカー・ワイルド",1854,1900,["ie","gb"],["literature"],"Oscar Wilde was an Irish poet and playwright known for his wit, flamboyant style, and masterful comedies. His only novel, The Picture of Dorian Gray, is a classic of Gothic fiction.","Wilde was born in Dublin to an intellectual family. He studied at Trinity College Dublin and Oxford, where he became a leading figure of the Aesthetic movement.","Wilde's brilliant comedies and epigrams defined the wit of the Victorian era. His imprisonment for homosexuality and subsequent works on suffering made him a symbol of artistic freedom.",[(1890,"Published The Picture of Dorian Gray"),(1895,"Premiered The Importance of Being Earnest"),(1895,"Imprisoned for gross indecency"),(1897,"Wrote De Profundis in prison"),(1900,"Died in Paris in exile")],[("The Importance of Being Earnest",1895,"Satirical comedy of manners mocking Victorian society"),("The Picture of Dorian Gray",1891,"Gothic novel about a man whose portrait ages while he remains young")],[("Be yourself; everyone else is already taken.","Attributed")])

p("anton-chekhov","Anton Chekhov","アントン・チェーホフ",1860,1904,["ru"],["literature"],"Anton Chekhov was a Russian playwright and short-story writer regarded as one of the greatest short-story writers in history. His plays revolutionized modern drama.","Chekhov was born in Taganrog, Russia. He studied medicine and practiced as a physician while writing, famously saying that medicine was his wife and literature his mistress.","Chekhov transformed both the short story and modern drama. His plays pioneered the use of subtext and indirect action, profoundly influencing 20th-century theater.",[(1888,"Published The Steppe"),(1895,"Premiered The Seagull"),(1899,"Premiered Uncle Vanya"),(1901,"Premiered Three Sisters"),(1904,"Premiered The Cherry Orchard; died of tuberculosis")],[("The Cherry Orchard",1904,"Play about a Russian aristocratic family facing the loss of their estate"),("The Seagull",1895,"Drama exploring art, love, and unfulfilled aspirations")],[("Medicine is my lawful wife, and literature is my mistress.","Letter, 1888")])

p("samuel-beckett","Samuel Beckett","サミュエル・ベケット",1906,1989,["ie","fr"],["literature"],"Samuel Beckett was an Irish novelist and playwright who was one of the last modernists and a key figure in the Theatre of the Absurd. He won the Nobel Prize in Literature in 1969.","Beckett was born in Dublin and studied at Trinity College Dublin. He moved to Paris in 1937, where he became part of James Joyce's circle and spent the rest of his life.","Beckett's minimalist works stripped theater and prose to their essentials, exploring the human condition with dark humor. Waiting for Godot is one of the most important plays of the 20th century.",[(1938,"Settled permanently in Paris"),(1953,"Premiered Waiting for Godot"),(1957,"Published Endgame"),(1969,"Awarded the Nobel Prize in Literature")],[("Waiting for Godot",1953,"Tragicomedy about two men waiting for someone who never arrives"),("Molloy",1951,"First novel of a trilogy exploring deterioration and the limits of language")],[("Ever tried. Ever failed. No matter. Try again. Fail again. Fail better.","Worstward Ho, 1983")])

p("haruki-murakami","Haruki Murakami","村上春樹",1949,None,["jp"],["literature"],"Haruki Murakami is a Japanese novelist whose surreal, melancholic fiction blends Western and Japanese literary traditions. He is one of the most widely read contemporary authors.","Murakami was born in Kyoto and grew up in Kobe. He ran a jazz bar in Tokyo before becoming a full-time writer after his first novel won a literary prize.","Murakami's blend of realism and surrealism, Western references, and exploration of loneliness has created a distinctive literary voice that resonates globally.",[(1979,"Published Hear the Wind Sing"),(1987,"Published Norwegian Wood"),(1994,"Published The Wind-Up Bird Chronicle"),(2009,"Published 1Q84")],[("Norwegian Wood",1987,"Realistic novel of love and loss set in 1960s Tokyo"),("Kafka on the Shore",2002,"Surreal novel weaving two narratives exploring fate and consciousness")],[("If you only read the books that everyone else is reading, you can only think what everyone else is thinking.","Norwegian Wood, 1987")])

p("chinua-achebe","Chinua Achebe","チヌア・アチェベ",1930,2013,["ng"],["literature"],"Chinua Achebe was a Nigerian novelist whose Things Fall Apart is the most widely read book in modern African literature. He is considered the father of African literature in English.","Achebe was born in Ogidi, Nigeria. He studied at the University of Ibadan and worked at the Nigerian Broadcasting Corporation before becoming a full-time writer and academic.","Things Fall Apart challenged Western narratives about Africa and established African fiction as a major literary force. Achebe's work inspired generations of African and postcolonial writers.",[(1958,"Published Things Fall Apart"),(1960,"Published No Longer at Ease"),(1967,"Supported Biafra during the Nigerian Civil War"),(2007,"Won the Man Booker International Prize")],[("Things Fall Apart",1958,"Novel about the impact of colonialism on Igbo society in Nigeria")],[("Until the lions have their own historians, the history of the hunt will always glorify the hunter.","Attributed")])

p("naguib-mahfouz","Naguib Mahfouz","ナギーブ・マフフーズ",1911,2006,["eg"],["literature"],"Naguib Mahfouz was an Egyptian novelist who was the first Arabic-language author to win the Nobel Prize in Literature. His Cairo Trilogy is considered a masterpiece of Arabic literature.","Mahfouz was born in Cairo and spent his entire life there. He studied philosophy at Cairo University and worked as a civil servant while writing prolifically.","Mahfouz brought the novel form to maturity in Arabic literature. His realistic depictions of Egyptian society and his experimentation with form influenced all subsequent Arabic fiction.",[(1956,"Published The Cairo Trilogy"),(1959,"Published Children of Gebelawi"),(1988,"Awarded the Nobel Prize in Literature"),(1994,"Survived assassination attempt by Islamist extremists")],[("The Cairo Trilogy",1956,"Three novels chronicling three generations of a Cairo family through modern Egyptian history")],[("You can tell whether a man is clever by his answers. You can tell whether a man is wise by his questions.","Attributed")])

p("alexander-pushkin","Alexander Pushkin","アレクサンドル・プーシキン",1799,1837,["ru"],["literature"],"Alexander Pushkin was a Russian poet and novelist who is considered the founder of modern Russian literature. His verse novel Eugene Onegin is a masterpiece of world literature.","Pushkin was born in Moscow to an aristocratic family. He was educated at the Imperial Lyceum and gained early fame for his poetry, though his liberal views led to periods of exile.","Pushkin created the modern Russian literary language and established the foundation upon which Tolstoy, Dostoevsky, and all subsequent Russian literature was built.",[(1820,"Exiled for political poems"),(1825,"Completed Boris Godunov"),(1831,"Published Eugene Onegin"),(1837,"Died from wounds sustained in a duel")],[("Eugene Onegin",1831,"Verse novel depicting Russian society through the story of a jaded aristocrat"),("Boris Godunov",1825,"Historical drama about the reign of Boris Godunov")],[("I loved you; even now I may confess, some embers of my love their fire retain.","I Loved You, 1829")])

p("virgil","Virgil","ウェルギリウス",-70,-19,["it"],["literature"],"Virgil was an ancient Roman poet, best known for the Aeneid, the epic poem that tells the story of Rome's founding and became the definitive literary work of the Roman Empire.","Virgil was born near Mantua in Cisalpine Gaul. He studied in Cremona, Milan, and Rome, and gained fame with his Eclogues before becoming Rome's national poet.","The Aeneid became the foundational myth of Rome and one of the most influential poems in Western literature. Virgil's influence extends through Dante, Milton, and all of Western literary tradition.",[(-42,"Published the Eclogues"),(-29,"Published the Georgics"),(-19,"Died leaving the Aeneid unfinished")],[("Aeneid",-19,"Epic poem tracing Rome's origins through the journey of the Trojan hero Aeneas"),("Georgics",-29,"Didactic poem on farming that celebrates the Italian countryside")],[("Fortune favors the bold.","Aeneid, Book X")])

p("fyodor-tyutchev","Fyodor Tyutchev","フョードル・チュッチェフ",1803,1873,["ru"],["literature"],"Fyodor Tyutchev was a Russian poet and diplomat considered one of the three greatest Russian poets alongside Pushkin and Lermontov. His philosophical lyrics explore nature and the cosmos.","Tyutchev was born into a noble family near Bryansk. He spent over 20 years abroad as a Russian diplomat in Munich and Turin before returning to Russia.","Tyutchev's poetry, combining Romantic intensity with philosophical depth, influenced Russian Symbolism and remains central to the Russian poetic tradition.",[(1822,"Entered diplomatic service in Munich"),(1836,"Published poems in Pushkin's journal The Contemporary"),(1854,"Published first collected poems")],[("Collected Poems",1854,"Philosophical and nature lyrics exploring cosmos, chaos, and human consciousness")],[("Russia cannot be understood with the mind alone.","Untitled poem, 1866")])

p("cao-xueqin","Cao Xueqin","曹雪芹",1715,1763,["cn"],["literature"],"Cao Xueqin was a Chinese novelist and author of Dream of the Red Chamber, one of China's Four Great Classical Novels and one of the greatest novels in world literature.","Cao Xueqin was born into a wealthy family that had served as bondservants to the Qing imperial house. The family's decline from wealth to poverty deeply influenced his masterwork.","Dream of the Red Chamber is considered the pinnacle of Chinese fiction, admired for its psychological depth, social realism, and lyrical beauty. An entire field of study, Redology, is devoted to it.",[(1740,"Began writing Dream of the Red Chamber"),(1754,"First 80 chapters circulated in manuscript"),(1763,"Died before completing the novel"),(1791,"First printed edition with 120 chapters published")],[("Dream of the Red Chamber",1754,"Novel depicting the decline of a wealthy Chinese family with extraordinary psychological and social detail")],[("Truth becomes fiction when the fiction is true; real becomes not-real where the unreal is real.","Dream of the Red Chamber")])

p("ovid","Ovid","オウィディウス",-43,17,["it"],["literature"],"Ovid was a Roman poet whose Metamorphoses, a narrative poem about transformations in Greek and Roman mythology, is one of the most influential works in Western literature.","Ovid was born in Sulmo, east of Rome. He studied rhetoric in Rome and traveled to Athens before devoting himself to poetry. Emperor Augustus exiled him to the Black Sea in 8 AD.","Ovid's Metamorphoses shaped Western art, literature, and culture more than almost any other classical work. Shakespeare, Dante, and countless artists drew directly from his mythological narratives.",[(-20,"Published Amores"),(-2,"Published Ars Amatoria"),(8,"Published Metamorphoses; exiled by Augustus"),(17,"Died in exile at Tomis")],[("Metamorphoses",8,"Narrative poem retelling Greek and Roman myths as a continuous history of transformations")],[("Dripping water hollows out stone, not through force but through persistence.","Epistulae Ex Ponto")])

write_people(P)
